ML:Post-Connections - Show comments
cairocoder01/disciple-tools-bulk-magic-link-sender pull request #1
Opened 2024-11-08 22:17 UTC by jlamanskygitt

2024-11-20 22:13 UTC, cairocoder01 requested changes
Looking good. We need to do some work on the API to create a comment. See the specific code comments for details on that.

2024-11-20 22:13 UTC, cairocoder01 commented on assets/post-connections.js
> +      }
Good job finding these APIs, but unfortunately we can't use them in the magic links. If you open the magic link in a browser that isn't logged in to DT, these APIs will return a 401 unauthenticated response. 

Instead, we'll need to create an API endpoint in this magic link template that can create comments. It will be like the API you created to get the comments but should be a POST type that receives the comment data and saves it. You can look at the existing `/update` endpoint as an example.

2024-11-20 22:13 UTC, cairocoder01 commented on magic-link/templates/post-connections.php
> +                    <dt-tile id="comments-tile" title="Comments"></dt-tile>
Can we put this inside the detail-content div and after the other dt-tile? It would be best if this is at the bottom of the detail panel. Putting it inside this div will allow the scroll behavior to work properly when it's taller than the available screen height.

2024-11-20 22:13 UTC, cairocoder01 commented on assets/post-connections.js
> +      jQuery.each(json['comments']['comments'], function(i, val) {
I'm trying to avoid using jQuery in this magic link. For a for loop, you can use standard js for..of:

```
for (const val of json['comments']['comments']) {
    // ...use `val`...
}
```

2024-11-20 22:13 UTC, cairocoder01 commented on assets/post-connections.js
> +  fetch(commentURL,{
Before we start this fetch, can we clear the comment container? There is a delay if I click a different item in the list while the detail panel is open; the form fields update instantly but the comments take a second or two. So there is a period of time where it's showing comments that don't match the form fields. I think it would be better if we emptied the comments tile before we start this API request and then fill it in again once we get the data for the post.

2024-11-21 19:55 UTC, jlamanskygitt reviewed
Resolved comments

2024-11-21 19:55 UTC, jlamanskygitt reviewed
Finished resolving comments

2024-11-26 20:55 UTC, cairocoder01 commented
@jlamanskygitt  If I access this in a browser that's not logged in to DT, I'm unable to save a new comment. It's using a normal DT API endpoint to save a comment that won't be accessible from the magic link. We'll need a new endpoint in this magic link that is just to save comments.

Make sure to do a pull before working on this more as I've merged in the main branch and made some other changes.

2024-12-24 17:29 UTC, cairocoder01 commented
That API works great. Nicely done! I just cleaned up the comment styles to match the frontend UI and will merge this.

2024-12-24 17:29 UTC, merged